### ISSUE TITLE
Suggestion: Integrate media queries into classes

### ISSUE THREAD

**Issue by melissamcewen** [murroak/ColmarAcademy#4]
So with responsive I and other developers often integrate the mobile and desktop versions in one class because there are some instances where in some breakpoints (like Ipad size) some elements are on the "mobile" and some are on "desktop." 

It also helps us understand that mobile (or desktop) is the default and each media query is an override. Here is the solution that codecademy provided for example: 

```css
/* Universal Component - Content Image Box */

.content-image-box {
  display: flex;
  padding: 1rem 0 1rem 1rem;
  border-bottom: 1px solid rgb(245, 245, 245);
}

.content-image-box:first-child {
  padding-top: 0;
}

.content-image-box:last-child {
  padding-bottom: 0;
  border-bottom: none;
}

.content-image-box .media-container {
  width: 35%;
}

.content-image-box .text-content {
  display: flex;
  flex-direction: column;
  justify-content: center;
  width: 65%;
  padding: 0 0.75rem 0 1rem;
}

.content-image-box h4 {
  padding-bottom: .5rem;
  font-size: 1.25rem;
  font-weight: bold;
}

.content-image-box p {
  padding-bottom: .5rem;
}

.content-image-box .mobile {
  display: none;
}


@media only screen and (max-width: 895px) {
  .content-image-box .desktop {
    display: none;
  }

  .content-image-box .mobile {
    display: block;
  }

  .content-image-box {
    padding-left: 0;
    border-bottom: none;
  }

  .content-image-box .media-container {
    width: 100%;
  }
}

```

I personally prefer
```css
.content-image-box {
  display: flex;
  padding: 1rem 0 1rem 1rem;
  border-bottom: 1px solid rgb(245, 245, 245);

 @media only screen and (max-width: 895px) {
    display: flex;
    padding: 1rem 0 1rem 1rem;
    border-bottom: 1px solid rgb(245, 245, 245);
 }
}

```
I know it means you repeat some stuff but I find it easier to read/understand.

But of course if this works for you better, there is nothing wrong with it, it's just what I and many  other developers do and some info on why we do it.
